version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/instance:/app/instance
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend